### ISSUE TITLE
pg_cron never ends job of "VACUUM VERBOSE"

### ISSUE THREAD

**Issue by ekeric13** [citusdata/pg_cron#148]
When I schedule a job of "VACUUM VERBOSE" or "VACUUM (VERBOSE, ANALYZE)" pg_cron executes job but never completes it. Specifically in "cron.job_run_details" the "end_time" column remains null.

<img width="1194" alt="Screen Shot 2021-09-07 at 4 13 57 PM" src="https://user-images.githubusercontent.com/6489651/132422056-98eade8c-11d6-4642-8a83-2e35e4f1b819.png">

Ended up having to manually cancel vacuum jobs that were "VERBOSE". I think the issue might be the output of the job is not suitable for return_message... which somehow causes the job to not exit properly... really just speculation though.
Replicated this behavior in multiple databases.

<img width="1189" alt="Screen Shot 2021-09-07 at 4 23 50 PM" src="https://user-images.githubusercontent.com/6489651/132422547-d22b2d33-3645-4eb6-a5bd-4d1fdb8c9503.png">

**Comment by TsinghuaLucky912** [comment]
pg13.1 + pg_cron1.3.1


![360截图20210908095303568](https://user-images.githubusercontent.com/49380232/132433510-bb4f4cd2-6f82-4ef2-bc1e-667f9f82fc70.jpg)

**Comment by TsinghuaLucky912** [comment]
I think you can change a database cluster (initdb) or restart the cluster after cleaning it

**Comment by ekeric13** [comment]
In order to install pg_cron in RDS I followed these docs:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html#PostgreSQL_pg_cron.enable

1. Update `shared_preload_libraries` to include `pg_cron` (I also updated `cron.database_name` to point to application database names instead of postgres)
2. Restart the DB
3. Run `CREATE EXTENSION pg_cron;`

Everything seems to be working as expected except the vacuum commands that are "VERBOSE".

I wanted to see if I could replicate this behavior in a non-RDS environment and so far I have not.

I created a dummy database in docker with pg_cron installed:

```
dockerfile


FROM postgres:12.5

RUN apt-get update

RUN apt-get -y install postgresql-12-cron

```

```
docker-compose.yml

version: '3'

services:
  db:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=test
    environment:
      POSTGRES_USER: tester
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
```

I have successfully run `VACUUM VERBOSE` and haven't found a way to break it.

I think at this point it might make sense to file a ticket with AWS about RDS. I already ran into one issue where pg_cron did not work with RDS Postgres version 12.2 and I had to do a minor upgrade to 12.5.

> I think you can change a database cluster (initdb) or restart the cluster after cleaning it

Are you saying to reboot the DB again and see if I can now do then perform "VACUUM VERBOSE"??

Do you have any suggestions on what I should ask AWS to look at?
